# Generated by Django 4.2.6 on 2023-11-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriversApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckdriver',
            name='birthday',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
