# Generated by Django 4.2.6 on 2023-11-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriversApp', '0003_alter_truckdriver_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckdriver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='driver_photos/'),
        ),
    ]
