# Generated by Django 4.2.6 on 2023-11-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriversApp', '0006_alter_truckdriver_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckdriver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='driver_photos/'),
        ),
    ]
