# Generated by Django 4.2.6 on 2023-11-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriversApp', '0007_alter_truckdriver_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckdriver',
            name='driving_license',
            field=models.FileField(blank=True, null=True, upload_to='driver_files/'),
        ),
        migrations.AddField(
            model_name='truckdriver',
            name='health_document',
            field=models.FileField(blank=True, null=True, upload_to='driver_files/'),
        ),
    ]
