# Generated by Django 4.2.6 on 2023-11-08 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriversApp', '0008_truckdriver_driving_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckdriver',
            name='driving_licence_expiration_date',
            field=models.DateField(default=datetime.date(2023, 11, 8)),
        ),
        migrations.AddField(
            model_name='truckdriver',
            name='health_document_expiration_date',
            field=models.DateField(default=datetime.date(2023, 11, 8)),
        ),
    ]
