# Generated by Django 4.2.6 on 2023-11-08 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DriversApp', '0009_truckdriver_driving_licence_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckdriver',
            name='driving_licence_expiration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='truckdriver',
            name='health_document_expiration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
