# Generated by Django 4.2.6 on 2023-11-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriversApp', '0010_alter_truckdriver_driving_licence_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckdriver',
            name='driving_licence_expiration_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='truckdriver',
            name='health_document_expiration_date',
            field=models.DateField(default=None),
        ),
    ]
