# Generated by Django 4.2.6 on 2023-11-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriversApp', '0015_truckdriver_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckdriver',
            name='notified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
