# Generated by Django 4.2.6 on 2023-11-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriversApp', '0016_truckdriver_notified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckdriver',
            name='health_document_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='truckdriver',
            name='health_document_notified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
