# Generated by Django 4.2.6 on 2023-11-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriversApp', '0018_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckdriver',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
