# Generated by Django 4.2.6 on 2023-11-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriversApp', '0019_truckdriver_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckdriver',
            name='driver_record_service_report_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truckdriver',
            name='truck_license',
            field=models.CharField(max_length=100),
        ),
    ]
