# Generated by Django 4.2.6 on 2023-11-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriversApp', '0020_truckdriver_driver_record_service_report_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckdriver',
            name='driver_report_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='truckdriver',
            name='driver_report_notified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
